spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
project:
  poster: poster/
  #poster: ${user.home}/movieflix/uploads/posters/  # Using absolute path

base:
  url: "http://localhost:8080"